// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzrChyEUDC0r1GWy6JShUcDOX4_w4egsE',
    appId: '1:765071982056:web:ebff09d212ee7c8fed785d',
    messagingSenderId: '765071982056',
    projectId: 'clone-6427e',
    authDomain: 'clone-6427e.firebaseapp.com',
    storageBucket: 'clone-6427e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-1IjpAvUHuHGuwsG_nNm6YSNgdcpPIM',
    appId: '1:765071982056:android:fabe2b4acded2e37ed785d',
    messagingSenderId: '765071982056',
    projectId: 'clone-6427e',
    storageBucket: 'clone-6427e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7xdfU9m0xLXzLNYyjjXpDbsuzz-6MtOE',
    appId: '1:765071982056:ios:8a755ab2b5733111ed785d',
    messagingSenderId: '765071982056',
    projectId: 'clone-6427e',
    storageBucket: 'clone-6427e.appspot.com',
    androidClientId: '765071982056-50plhs0uud7g345k3gm2uuhmt3636a69.apps.googleusercontent.com',
    iosClientId: '765071982056-oh8i66bhh3fft3l9kufkvkmkk28d1eg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7xdfU9m0xLXzLNYyjjXpDbsuzz-6MtOE',
    appId: '1:765071982056:ios:8a755ab2b5733111ed785d',
    messagingSenderId: '765071982056',
    projectId: 'clone-6427e',
    storageBucket: 'clone-6427e.appspot.com',
    androidClientId: '765071982056-50plhs0uud7g345k3gm2uuhmt3636a69.apps.googleusercontent.com',
    iosClientId: '765071982056-oh8i66bhh3fft3l9kufkvkmkk28d1eg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonClone',
  );
}
