// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85tio1AUQQBdla2A25H4fCOqTFJ2Dnuo',
    appId: '1:652605832153:web:69aff4872ad748ed4fb7c8',
    messagingSenderId: '652605832153',
    projectId: 'csr-project-3d0cc',
    authDomain: 'csr-project-3d0cc.firebaseapp.com',
    storageBucket: 'csr-project-3d0cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd2675nSsoLw0xcHXGVOjVXIrPa11qLM8',
    appId: '1:652605832153:android:5683e0b8e76df16d4fb7c8',
    messagingSenderId: '652605832153',
    projectId: 'csr-project-3d0cc',
    storageBucket: 'csr-project-3d0cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO3LrIxJiXfwaF4gjTsnsHoKhDcdD3ty8',
    appId: '1:652605832153:ios:8600e51f9645a3ec4fb7c8',
    messagingSenderId: '652605832153',
    projectId: 'csr-project-3d0cc',
    storageBucket: 'csr-project-3d0cc.appspot.com',
    androidClientId: '652605832153-0vav9b7dtpqbqbb24652ubituillhgn9.apps.googleusercontent.com',
    iosClientId: '652605832153-4gmgctt7v37e90i83ppfqcdm2vujt5n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.csr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO3LrIxJiXfwaF4gjTsnsHoKhDcdD3ty8',
    appId: '1:652605832153:ios:8600e51f9645a3ec4fb7c8',
    messagingSenderId: '652605832153',
    projectId: 'csr-project-3d0cc',
    storageBucket: 'csr-project-3d0cc.appspot.com',
    androidClientId: '652605832153-0vav9b7dtpqbqbb24652ubituillhgn9.apps.googleusercontent.com',
    iosClientId: '652605832153-4gmgctt7v37e90i83ppfqcdm2vujt5n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.csr',
  );
}
